return {
    FA_CHECK_CIRCLE = "\u{F058}",
    FA_THUMB_TACK = "\u{F08D}",
    FA_EXCLAMATION_CIRCLE = "\u{F06A}",
    FA_INFO_CIRCLE = "\u{F05A}",
    FA_QUESTION_CIRCLE = "\u{F059}",
    FA_GLOBE = "\u{F0AC}",
    FA_DATABASE = "\u{F1C0}",
    FA_REFRESH = "\u{F021}",
    FA_BOOK = "\u{F02D}",
    FA_DOWNLOAD = "\u{F019}",
    FA_ELLIPSIS_VERTICAL = "\u{F142}",
    FA_MAGNIFYING_GLASS = "\u{F002}",
    FA_PLUG = "\u{F1E6}",
    FA_TIMES = "\u{F00D}",
    FA_EXCHANGE = "\u{F0EC}",
    FA_HOURGLASS = "\u{231B}",
    FA_FOLDER = "\u{F07B}",
    FA_PLAY = "\u{F04B}",
    FA_SHARE = "\u{F064}",
    FA_TRASH = "\u{F1F8}",
    UNICODE_ARROW_LEFT = "\u{25C2}",
    UNICODE_STAR = "\u{2605}",
    UNICODE_STAR_OUTLINE = "\u{2606}",
}
